config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('education.urls')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

education/models.py
from django.db import models


class Course(models.Model):
    title = models.CharField(max_length=50, verbose_name='Kurs nomi', unique=True)
    description = models.TextField(blank=True, null=True, verbose_name="Kurs haqida")
    photo = models.ImageField(upload_to='photos/', blank=True, null=True, verbose_name='Rasmi')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'kurs '
        verbose_name_plural = 'kurslar'


class Student(models.Model):
    name = models.CharField(max_length=50, verbose_name='Talaba ismi')
    email = models.EmailField(max_length=100, unique=True, verbose_name='Email manzili')
    enrolled_at = models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqti')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Kursi')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'talaba '
        verbose_name_plural = 'Talabalar'
        permissions = [('test permission', 'test permission'),]

templates/add_course.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock title %}

{% block main %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex justify-content-around">
        <input type="submit" value="Create" class="btn btn-outline-primary btn-rounded">
        <a href="{% url 'home' %}" class="btn btn-outline-primary btn-rounded">Cancel</a>
    </div>
</form>
{% endblock main %}

templates/add_student.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock title %}

{% block main %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-flex justify-content-around">
        <input type="submit" value="Add" class="btn btn-outline-primary btn-rounded">
        <a href="{% url 'home' %}" class="btn btn-outline-primary btn-rounded">Cancel</a>
    </div>
</form>
{% endblock main %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load my_tags %}
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    {% include 'components/_style.html' %}
</head>
<body>
{% include 'components/_navbar.html' %}
<main>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger d-flex justify-content-center" role="alert">
                  {{ error }}
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger d-flex justify-content-center" role="alert">
              {{ error }}
            </div>
        {% endfor %}
    {% endif %}



    {% if messages %}
        <ul class="messages d-flex justify-content-center">
            {% for message in messages %}
            <li class="alert alert-{% if message.tags == 'error' %}danger {% else %}{{ message.tags }} {% endif %}" id="unordered_list">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}



{% block main %}
{% endblock main %}

    <!-- Back to top button -->
    <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-floating btn-lg" id="btn-back-to-top">
      <i class="fas fa-arrow-up"></i>
    </button>
    <!-- Back to top button -->

</main>

{% include 'components/_script.html' %}
{% include 'components/_footer.html' %}
</body>
</html>

templates/courses.html
{% extends 'base.html' %}
{% load my_tags %}

{% block title %}
{{ title }}
{% endblock title %}

{% block main %}

    <div class="d-flex justify-content-center mb-5">
        <h3 id="courses">Available Courses</h3>
    </div>
    <!--cards-->
        <div class="row row-cols-1 row-cols-md-3 g-4 mb-5 px-5">
            {% all_courses as courses %}
          {% for course in courses %}
        <div class="col">
          <div class="card h-100">
              {% if course.photo %}
                  <a href="{% url 'course_detail' course.id %}">
                        <img src="{{ course.photo.url }}" class="card-img-top" title="{{ course.title }}" alt="courses" data-mdb-tooltip-init/>
                  </a>
              {% endif %}
            <div class="card-body">
                <a href="{% url 'course_detail' course.id %}">
                    <h5 class="card-title">{{ course.title }}</h5>
                </a>
              <p class="card-text">
                  <strong>Course:</strong> {{ course.title }} <br>
                  About: {{ course.description|truncatewords:20 }}
              </p>
            </div>
              <div class="card-footer">
                <small class="text-muted d-flex justify-content-center">{{ course.created_at }}</small>
              </div>
          </div>
        </div>
          {% endfor %}
      </div>
    <!--cards-->

    <!--students-->
    <div class="d-flex justify-content-center mb-5">
        <h3 id="students">Students</h3>
    </div>
    <!--students-->

    <!--students card-->
    <div class="container">
        <div class="row">
            {% for student in students %}
            <div class="col-md-4 mb-4">
                <div class="card text-center">
                    <div class="card-header">{{ student.course }}</div>
                    <div class="card-body">
                        <h5 class="card-title">{{ student.name }}</h5>
                        <p class="card-text"><strong>Email:</strong> {{ student.email }}</p>
                        <p class="card-text"><strong>Enrolled date:</strong> {{ student.enrolled_at }}</p>
                        <a href="{% url 'student_detail' student.id %}" class="btn btn-primary" data-mdb-ripple-init>Batafsil</a>
                    </div>
                    <div class="card-footer text-muted">{{ student.enrolled_at }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <!--students card-->

{% endblock main %}

templates/delete_confirm.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock title %}
{% block main %}

<form method="post">
    {% csrf_token %}
    <div class="d-flex justify-content-center"><h2>Kurs nomi: {{ course.title }}</h2></div>
    <div class="d-flex justify-content-around">
        <button type="submit" class="btn btn-outline-primary btn-rounded" data-mdb-ripple-init  data-mdb-ripple-color="dark">Delete</button>
        <a href="{% url 'course_detail' course.id %}" class="btn btn-outline-primary btn-rounded" data-mdb-ripple-init  data-mdb-ripple-color="dark">Cancel</a>
    </div>
</form>
{% endblock main %}

templates/delete_confirm_student.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock title %}

{% block main %}

<form method="post">
    {% csrf_token %}
    <div class="d-flex justify-content-center"><h2>Talaba ismi: {{ student.name }}</h2></div>
    <div class="d-flex justify-content-around">
        <button type="submit" class="btn btn-outline-primary btn-rounded" data-mdb-ripple-init  data-mdb-ripple-color="dark">Delete</button>
        <a href="{% url 'student_detail' student.id %}" class="btn btn-outline-primary btn-rounded" data-mdb-ripple-init  data-mdb-ripple-color="dark">Cancel</a>
    </div>
</form>

{% endblock main %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock title %}

{% block main %}

<!--cards-->
<div class="row row-cols-1 row-cols-md-12 g-4">
<div class="col">
  <div class="card h-100">
      {% if course.photo %}
    <img src="{{ course.photo.url }}" class="card-img-top" alt="Courses" title="{{ course.title }}" data-mdb-tooltip-init/>
      {% endif %}
    <br>
      <div class="card-body">
          {% if request.user.is_authenticated %}
        <div class="d-flex flex-row-reverse">
            {% if perms.education.delete_course %}
            <a href="{% url 'delete_course' course.id %}"><i class="fas fa-trash-can"></i></a> &nbsp; &nbsp; &nbsp;
            {% endif %}

            {% if perms.education.change_course %}
          <a href="{% url 'update_course' course.id %}"><i class="fas fa-pen"></i></a>
            {% endif %}
      </div>
          {% endif %}
        <a href="{% url 'home' %}">
            <h5 class="card-title">{{ course.title }}</h5>
        </a>
      <p class="card-text">
          <strong>Name:</strong> {{ course.title }}<br>
          <strong>Starts from:</strong> {{ course.created_at }} <br>
          <strong>About:</strong> {{ course.description|linebreaks }}
      </p>
    </div>
    <div class="card-footer d-flex justify-content-around">
      <small class="text-muted">{{ course.created_at }}</small>
    </div>
  </div>
</div>
</div>
<!--cards-->
<div class="mt-5 d-flex justify-content-center mb-5">
    <a href="{% url 'home' %} " class="btn btn-outline-primary btn-rounded" data-mdb-ripple-init  data-mdb-ripple-color="dark">
        Ortga</a>
</div>

{% endblock main %}

templates/index.html
{% extends 'base.html' %}
{% load my_tags %}

{% block title %}
{{ title }}
{% endblock title %}

{% block main %}

    <div class="d-flex justify-content-center mb-5">
        <h3 id="courses">Available Courses</h3>
    </div>
    <!--cards-->
        <div class="row row-cols-1 row-cols-md-3 g-4 mb-5 px-5">
            {% all_courses as courses %}
          {% for course in courses %}
        <div class="col">
          <div class="card h-100">
              {% if course.photo %}
                  <a href="{% url 'course_detail' course.id %}">
                        <img src="{{ course.photo.url }}" class="card-img-top" title="{{ course.title }}" alt="courses" data-mdb-tooltip-init/>
                  </a>
              {% endif %}
            <div class="card-body">
                <a href="{% url 'course_detail' course.id %}">
                    <h5 class="card-title">{{ course.title }}</h5>
                </a>
              <p class="card-text">
                  <strong>Course:</strong> {{ course.title }} <br>
                  About: {{ course.description|truncatewords:20 }}
              </p>
            </div>
              <div class="card-footer">
                <small class="text-muted d-flex justify-content-center">{{ course.created_at }}</small>
              </div>
          </div>
        </div>
          {% endfor %}
      </div>
    <!--cards-->

    <!--students-->
    <div class="d-flex justify-content-center mb-5">
        <h3 id="students">Students</h3>
    </div>
    <!--students-->

    <!--students card-->
    <div class="container">
        <div class="row">
            {% for student in students %}
            <div class="col-md-4 mb-4">
                <div class="card text-center">
                    <div class="card-header">{{ student.course }}</div>
                    <div class="card-body">
                        <h5 class="card-title">{{ student.name }}</h5>
                        <p class="card-text"><strong>Email:</strong> {{ student.email }}</p>
                        <p class="card-text"><strong>Enrolled date:</strong> {{ student.enrolled_at }}</p>
                        <a href="{% url 'student_detail' student.id %}" class="btn btn-primary" data-mdb-ripple-init>Batafsil</a>
                    </div>
                    <div class="card-footer text-muted">{{ student.enrolled_at }}</div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <!--students card-->

{% endblock main %}

templates/student_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ title }}
{% endblock title %}

{% block main %}

<!--cards-->
<div class="d-flex justify-content-center">
  <div class="card mb-5" style="max-width: 540px;" >
      <div class="col-md-12">
        <div class="card-body">
          <h5 class="card-title">{{ student.course }} - talabasi</h5>
          <p class="card-text"><strong>Ism:</strong> {{ student.name }}</p>
          <p class="card-text"><strong>Email:</strong> {{ student.email }}</p>
          <p class="card-text"><strong>Ro'yxatdan o'tilgan vaqt:</strong> {{ student.enrolled_at }}</p>
          <div class="d-flex justify-content-around">
            <a href="{% url 'home' %}" class="btn btn-primary" data-mdb-ripple-init>Ortga</a>

            <!--dropdown button-->
          <div class="btn-group dropup">
            <button
            type="button" class="btn btn-primary dropdown-toggle"
            data-mdb-dropdown-init
            data-mdb-ripple-init aria-expanded="false">
              More
            </button>
            <ul class="dropdown-menu">
              {% if perms.education.delete_student %}
              <li><a class="dropdown-item" href="{% url 'delete_student' student.id %}">Delete</a></li>
              <li><a class="dropdown-item" href="{% url 'update_student' student.id %}">Update</a></li>
              {% else %}
              <div class="alert alert-danger d-flex justify-content-center" role="alert">
                  Talabalar ustida hech qanday amal bajara olmaysiz!!!
                </div>
              {% endif %}
            </ul>
          </div>
            <!--dropdown button-->

          </div>
        </div>
      </div>
  </div>
</div>
<!--cards-->


{% endblock main %}