config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('education.urls')),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

education/models.py
from django.db import models


class Course(models.Model):
    title = models.CharField(max_length=50, verbose_name='Kurs nomi', unique=True)
    description = models.TextField(blank=True, null=True, verbose_name="Kurs haqida")
    photo = models.ImageField(upload_to='photos/', blank=True, null=True, verbose_name='Rasmi')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'kurs '
        verbose_name_plural = 'kurslar'


class Student(models.Model):
    name = models.CharField(max_length=50, verbose_name='Talaba ismi')
    email = models.EmailField(max_length=100, unique=True, verbose_name='Email manzili')
    enrolled_at = models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan vaqti')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Kursi')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'talaba '
        verbose_name_plural = 'Talabalar'
        permissions = [('test permission', 'test permission'),]

templates/components/_footer.html
<footer class="bg-body-tertiary text-center">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Telegram -->
      <a
      data-mdb-ripple-init
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998;"
        href="https://t.me/ahmadjonovazizbek" target="_blank"
        role="button"
        ><i class="fab fa-telegram"></i
      ></a>

      <!-- Instagram -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac;"
        href="https://instagram.com/1azikk1" target="_blank"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Github -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1"
        style="background-color: #333333;"
        href="https://github.com/1azikk1" target="_blank"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    <a class="text-body" href="{% url 'home' %}">
      Follow us on social media <br>
      Thank you for your attention🔥</a>
  </div>
  <!-- Copyright -->
</footer>

templates/components/_navbar.html
{% load static %}
{% load my_tags %}

<!--Navbar starts here-->
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary mt-3 mb-5">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand me-2" href="{% url 'home' %}">
      <img
        src="{% static 'images/logo.png' %}"
        height="50"
        alt="EduHub"
        loading="lazy"
        style="margin-top: -1px; border-radius: 10px;"
      />
    </a>

    <!-- Toggle button -->
    <button
      data-mdb-collapse-init
      class="navbar-toggler"
      type="button"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Asosiy Sahifa</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#courses">Kurslar</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#students">Talabalar</a>
        </li>

        {% if perms.education.add_course %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_course' %}">Kurs qo'shish</a>
        </li>
        {% endif %}

        {% if perms.education.add_student %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student' %}">Talaba qo'shish</a>
        </li>
        {% endif %}
      </ul>
      <!-- Left links -->

      <!--dropdown button-->
     <div class="dropdown">
        <button
          class="btn btn-primary dropdown-toggle"
          type="button"
          id="dropdownMenuButton"
          data-mdb-dropdown-init
          data-mdb-ripple-init
          aria-expanded="false"
        >
          Courses
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% all_courses as courses %}
          {% for course in courses %}
          <li><a class="dropdown-item" href="{% url 'students_by_course' course.id %}">{{ course.title }}</a></li>
          {% endfor %}
        </ul>
      </div>
      <!--dropdown button-->
      &nbsp; &nbsp;
      {{ request.user.username }}

        {% if not request.user.is_authenticated %}

      <div class="d-flex align-items-center">
        <a href="{% url 'user_login' %}" data-mdb-ripple-init class="btn btn-link px-3 me-2">
          Login
        </a>
        <a  href="{% url 'user_register' %}" data-mdb-ripple-init  class="btn btn-primary me-3">
          Sign up
        </a>
          {% else %}
          &nbsp; &nbsp;
        <!-- Avatar -->
        <div class="dropdown">
          <a
            data-mdb-dropdown-init
            class="dropdown-toggle d-flex align-items-center hidden-arrow"
            href="#"
            id="navbarDropdownMenuAvatar"
            role="button"
            aria-expanded="false"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
              class="rounded-circle"
              height="40"
              alt="Black and White Portrait of a Man"
              loading="lazy"
            />
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuAvatar"
          >
            <li>
              <a class="dropdown-item" href="{% url 'home' %}">My profile</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'home' %}">Settings</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'user_logout' %}">Logout</a>
            </li>
          </ul>
        </div>
          {% endif %}
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!--Navbar ends here-->

templates/components/_script.html
{% load static %}

<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.1.0/mdb.umd.min.js"
></script>
<!--MDB -->
<script src="{% static 'js/script.js' %}"></script>

templates/components/_style.html
{% load static %}

<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.1.0/mdb.min.css"
  rel="stylesheet"
/>

<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link rel="icon" href="{% static 'images/logo.png' %}">